### ISSUE TITLE
有需要幫忙嗎 

### ISSUE THREAD

**Issue by yaodehaung** [jsgao0/Evacuation#1]
我是想參加你的專案  但不知道怎麼幫忙
我會寫nodejs 與前端的技能

**Comment by jsgao0** [comment]
@yaodehaung  太棒了！ 我在[hackpad](https://g0v.hackpad.com/ml1Hdx1ZUeb)有開了一些TODO list，你可以看一下[API](https://github.com/jsgao0/EvacuationRESTful)的部分。那個Respository主要分成三個部分：converter、importer和API server。 open data在hackpad裡面有，要寫converter轉成JSON（可以參考），要自己找
pattern。 有問題再跟我說 ：）

**Comment by yaodehaung** [comment]
有channel 嗎?
(slack or fb )

**Comment by jsgao0** [comment]
https://g0v-tw.slack.com/archives/em

**Comment by yaodehaung** [comment]
加了
